<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon />
    <OutputType>Exe</OutputType>
    <StartupObject />
    <Nullable>enable</Nullable>
    <PackageId>GitIssue.Tool</PackageId>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>gitissue</ToolCommandName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.3.0" />
    <PackageReference Include="GitVersion.MsBuild" Version="6.8.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Humanizer.Core" Version="3.0.10" />
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.6.0" />
    <PackageReference Include="Pastel" Version="7.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="System.Linq.Async" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitIssue\GitIssue.csproj" />
  </ItemGroup>

</Project>