name: build

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: true
          fetch-depth: 0
      - name: Build
        uses: cake-build/cake-action@v1
        with:
          target: Test
