name: deploy

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: true
          fetch-depth: 0
      - name: Push
        uses: cake-build/cake-action@v1
        with:
          target: Push
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
