name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release "src/GitIssue.sln"
    - name: Test
      run: dotnet test --configuration Release "src/GitIssue.sln"
    - name: Publish
      run: dotnet publish "src/GitIssue.Tool/GitIssue.Tool.csproj" --framework netcoreapp3.1 --runtime win10-x64 --self-contained
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: GitIssue-win10-x64
        path: src/output/GitIssue.Tool/bin/Debug/netcoreapp3.1/win10-x64/publish/GitIssue.Tool.exe
