name: build

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: true
        fetch-depth: 0
    - name: Setup
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 3.1.301    
    - name: Restore
      run: dotnet tools restore
    - name: Build
      run: dotnet cake
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: GitIssue-win10-x64
        path: .publish/GitIssue.Tool.exe
